basePath: /api/v1
definitions:
  go-swagger-example_internal_models.CreateTodoInput:
    properties:
      task:
        description: binding required nếu gửi yêu cầu trống thì báo lỗi
        type: string
    required:
    - task
    type: object
  go-swagger-example_internal_models.Todo:
    properties:
      completed:
        type: boolean
      id:
        type: string
      task:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Go Swagger Example API
  version: "1.0"
paths:
  /todos:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/go-swagger-example_internal_models.Todo'
            type: array
      summary: ABABBABABA
      tags:
      - todos
    post:
      consumes:
      - application/json
      parameters:
      - description: Nội dung công việc
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/go-swagger-example_internal_models.CreateTodoInput'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/go-swagger-example_internal_models.Todo'
      summary: Tạo
      tags:
      - todos
swagger: "2.0"
