basePath: /api/v1
definitions:
  go-swagger-example_internal_models.Todo:
    properties:
      completed:
        type: boolean
      id:
        type: string
      task:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  title: Go Swagger Example API
  version: "1.0"
paths:
  /todos:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/go-swagger-example_internal_models.Todo'
            type: array
      summary: Lấy danh sách công việc
      tags:
      - todos
swagger: "2.0"
